### PR TITLE
Add Chart

### PR DESCRIPTION
**Pull request by Hjklvfr**
resolve https://github.com/1712n/dn-institute/issues/291

Add Chart with market and pair selection

Use React TS

### CODE REVIEW

**Comment by Hjklvfr** [comment]
Hi @marina-chibizova!
You can check it on https://hjklvfr.github.io/dn-institute/market-health/docs/market-health-metrics/
Some fonts and js files cannot be loaded due to incorrect routing of user pages.

**Comment by marina-chibizova** [comment]
looks the same for me
image

**Comment by Hjklvfr** [comment]
> looks the same for me image

long loading
I'll add a loader

**Comment by evgenydmitriev** [comment]
@Hjklvfr, are you planning to address the comment, or we can close this pr?

**Comment by Hjklvfr** [comment]
@evgenydmitriev 
I redid it
made chart support for all metrics
I'm testing now
I'll push it in 1-2 days

**Comment by Hjklvfr** [comment]
@marina-chibizova @evgenydmitriev 
https://hjklvfr.github.io/dn-institute/market-health/docs/market-health-metrics/
I set up the secrets but if it doesn't show up 
image

Bottom 3 charts are displayed after clicking on one of the top chart

**Comment by marina-chibizova** [comment]
@Hjklvfr cool! Quick notes from my side:

- I still can't render it in a codespace
- Two top charts look different from the rest
- What happens when user clicks on green and blue captions of the top two charts? Why does it affect the results of the charts below?
- Looks like lower charts only appear after a click on the top two

**Comment by Hjklvfr** [comment]
Short answers from my side:
1. I’ll try to run it myself in codespace and fix the problems 
2. I did the first two charts as I see. 
The bottom three charts are made in accordance with the articles in the project.  
3-4.  Lower graphs can only appear when a datapoint from the first charts is selected. Because one datapoint have own data for last charts.

**Comment by Hjklvfr** [comment]
Short answers from my side:
1. I added secrets for codespaces. You can reload.
2. I did the first two charts as I see. 
The bottom three charts are made in accordance with the articles in the project.  
3-4.  Lower graphs can only appear when a datapoint from the first charts is selected. Because one datapoint have own data for last charts.

**Comment by Hjklvfr** [comment]
@marina-chibizova Did what I did matches to what needed to be done?

**Comment by marina-chibizova** [comment]
@Hjklvfr the thing is it doesn't make much sense to visualize every 1m data point separately. Normally people would plot data over a time, like several hours or days to be able to see anomalous spikes. Two top charts make more sense to me. Although putting buy-sell ratio and buy-sell ration absolute on one chart is not that beneficial, since they show the same metric, just a bit differently. These things can be fixed though. 

What's more important is how sensible the widget solution is, and how much maintenance would it require. To asset it I would ask @evgenydmitriev. If it's fine we can proceed with visualization fixes

**Comment by marina-chibizova** [comment]
> If it needed I can add more logic for aggregate or/and union data. I did base for next steps.
> May be it is more sense to sum all 1m first digit metric data(for example).
> Every line in plot can be hiden by default or by click on it at bottom.

As I said, all this can be dealt with after we have a green light for service logic

> Also I'm confused about dictionary endpoint. May be it would be more convenient if I can load all pair or markets, or search these. For now it is difficult to switch from one rare pair to another from another market.

I didn't quite get what you are saying, /dictionary is very flexible, you can get all the markets at once, or a specific pair with all supported marketvenues or a marketvenue with all supported pairs, or search specific market (unique combination of marketvenue and pair)

**Comment by evgenydmitriev** [comment]
Comments not addressed. Clossing.

**Pull request closed without merging**
