### PR TITLE
2019-07-12-BITpoint

### PR DESCRIPTION
**Pull request by LiquidVac**

### CODE REVIEW

**Review by eric-oconnor — DISMISSED** [review]
Reference the [Wiki PR Approval Criteria](https://github.com/1712n/dn-institute#wiki-pr-approval-criteria) for the structure and required headers, please do not add other categories.  Make sure to add quote marks "" where indicated in wiki guide.

**Comment by danisztls** [comment]
@eric-oconnor Would this referencing system be better? [^example]

[^example]: This is an example footnote reference.

**Comment by eric-oconnor** [comment]
> @eric-oconnor Would this referencing system be better? [1](#user-content-fn-example-9852b48400b4ca06ca65671588a1c1d2)
> 
> ## Footnotes
> 1. This is an example footnote reference. [↩](#user-content-fnref-example-9852b48400b4ca06ca65671588a1c1d2)

Regarding the submissions this seems more stylistic than necessary for accuracy.  I am not the one to ask for that

**Comment by LiquidVac** [comment]
Added quote marks, links corrected.

> `BITPoint re-opened trading services on after a successful safety assessment of the platform's wallet.` ❌ False. The search results show that Bitpoint cryptocurrency exchange was hacked and lost $32 million in 2019. The exchange has not yet resumed services and is still monitoring the situation to complete a comprehensive review of all security measures. There is no evidence to suggest that they have re-opened trading services after a successful safety assessment.
> 
links to proves:
https://www.cryptonewsz.com/bitpoint-japanese-crypto-exchange-re-opens-for-trade-services-after-28-million-hack-in-mid-of-july/
https://finance.yahoo.com/news/japanese-crypto-exchange-bitpoint-restarting-014200443.html

**Comment by evgenydmitriev** [comment]
@LiquidVac please [add the link](https://github.com/1712n/dn-institute#:~:text=Add%20markdown%20links%20directly%20to%20your%20text) directly to the part of the article that the bot got wrong.

**Review by evgenydmitriev — APPROVED** [review]

**Comment by albina-at-inca** [comment]
> Thanks, @LiquidVac! 2339 characters were added or changed in this [PR](https://github.com/1712n/dn-institute/pull/116.diff) and your contribution is worth $116.95. @albina-at-inca will process your payment.

@LiquidVac please note, all the payouts are done at the end of the month. Usually it is the 28th of the month. Please let me know if you have any questions.

**Pull request merged**
