### PR TITLE
Poloniex 2023_10_26 - 2023_10_27

### PR DESCRIPTION
**Pull request by Annyvichi**

### CODE REVIEW

**Comment by Annyvichi** [comment]
Hi! Would you review my article, please?

**Review by sofiasedlova — CHANGES_REQUESTED** [review]
Thanks for your PR! You did a great job!

It's cool that you found numerous useful metrics from our Manipulation Metrics API. Your report covers trade-size anomalies, and you've attempted to interconnect transaction-related metrics, which definitely adds to the evidential aspect of the whole report. Here are some general points to focus on if you want to continue working on the report text to publish it:

- Start by outlining the key findings at the beginning. Make assumptions about what really happened in the market during the specified time range of interest. Provide interpretations and add financial insights.

- Try to avoid irrelevant comparisons. You never know what low-tier exchanges like [HitBTC](https://cointelegraph.com/news/bitwise-calls-out-to-sec-95-of-bitcoin-trade-volume-is-fake-real-market-is-or#:~:text=Among%20the%2073%20exchanges%20that%20Bitwise%20condemned%20as%20displaying%20fake%20volumes%20are%20OKEx%2C%20HitBTC%20and%20Huobi) might be hiding behind the scenes.

- Use ChatGPT to better structure your ideas and proofread your text. We appreciate it when contributors utilize powerful language models for their texts.

- Ensure that your charts are easy to read. Sometimes, less information is better.

- Do not use metrics that you're not comfortable with. Concentrate on those that are relevant to the case.

**Comment by Annyvichi** [comment]
Thank you! I try to continue :)

**Comment by Annyvichi** [comment]
@sofiasedlova would you review, please? I finished the corrections, but ready to continue. 

I'm not sure about my conclusions, and also noticed that
hourly mode(wbtc-usdt) * hourly vwap(wbtc-usdt) = $92 -95.
Then probably the most frequent trade size is $100 minus commission? Then can it be not manipulation? What do you think about the wbtc-usdt section?

I tried to find similar patterns, there are some timestamps with 
mode(wbtc-usdt) * vwap(wbtc-usdt) = around $100, $200 
on other exchanges, but there is no consistency. 

Here is that calculation for Poloniex 26/10 - 27/10:

	         mode		  vwap			         mode*vwap
10:00	0.00275 	        34636.47136287908 	95.25029624791746
11:00	0.00269 	        34439.35071774314 	92.64185343072904
12:00	0.00269 	        34319.87610749857 	92.32046672917114
13:00	0.00272 	        34348.320553609075 	93.42743190581669
14:00	0.00272 	        34300.080294613195 	93.2962184013479
15:00	0.00271 	        34153.667704306135 	92.55643947866963
16:00	0.00278 	        34204.74725903882 	95.08919738012791
17:00	0.00274 	        34190.28973107803 	93.6813938631538
18:00	0.00273 	        34235.32767712406 	93.46244455854868
19:00	0.0027 	        34233.333181385155 	92.42999958973992
20:00	0.00269 	        34294.14096998711 	92.25123920926532
21:00	0.00269 	        34299.73481674404 	92.26628665704148
22:00	0.00273 	        34309.338135425955 	93.66449310971285
23:00	0.00278 	        34310.395686927004 	95.38290000965706
00:00	0.0027 		34266.485275012375 	92.51951024253341
01:00	0.00279 	        34210.98340336284 	95.44864369538233
02:00	0.00274 	        34129.872591195315 	93.51585089987516
03:00	0.00274 	        34163.570830922734 	93.60818407672828
04:00	0.00271 	        34145.735978462784 	92.53494450163416
05:00	0.0027 		34139.83385438617 	92.17755140684265
06:00	0.00271 	        34167.598197864034 	92.59419111621153
07:00	0.00271 	        34157.96507841566 	92.56808536250645
08:00	0.00274 	        34129.72607001862 	93.51544943185102
09:00	0.0027 		34179.17599703797 	92.28377519200252

**Comment by Annyvichi** [comment]
@sofiasedlova I found out that for ZEC-USDT mode*vwap = $92-95 also, the file is attached.
It is the same for avax-usdt, dot-usdt and nft-usdt. Can it be real people using $100 value?
[mode, vwap.txt](https://github.com/1712n/dn-institute/files/13536838/mode.vwap.txt)

**Comment by Annyvichi** [comment]
> @Annyvichi tag me in this issue if you want me to review the finalized changes to the report text

@sofiasedlova I do!

**Comment by Annyvichi** [comment]
@sofiasedlova, ready for review now

**Comment by sofiasedlova** [comment]
@Annyvichi Alright, these were your last changes to the report?

**Comment by Annyvichi** [comment]
> @Annyvichi Alright, these were your last changes to the report?

@sofiasedlova, yes. I don't know how much I don't know about the subject of the article, so changing seems useless right now

**Comment by sofiasedlova** [comment]
@Annyvichi Thank you for your submission. I have carefully reviewed the article and appreciate the effort put into it. 

While the factual findings present intriguing possibilities for further investigation, I believe the supporting evidence could be strengthened to reinforce your arguments. Additionally, enhancing the consistency and coherence throughout the report would significantly improve its overall impact. 

I look forward to seeing any revisions you might consider based on this feedback, and I am eager to review any further work you submit.

**Pull request closed without merging**
