### PR TITLE
simple-fixes

### LINKED ISSUE #234: Fix menus
- Hide MVT
- Make "Crypto Attacks" collapsible
- Delete "External"

### PR DESCRIPTION
**Pull request by marina-chibizova**
fixes #234 

@danisztls I need your help with making "Infrastructure Resilience" (former "Crypto Attacks") collapsible. Just need 3 categories in the left menu:

- Market health
- Infrastructure Resilience 
- Education

I played with it a bit in a codespace using [this](https://github.com/alex-shpak/hugo-book/blob/3f1bcccbfb247da44ab5410a97576c0bf6da103b/exampleSite/content.en/docs/example/collapsed/_index.md?plain=1#L2) as a reference, but it didn't work, at least hasn't rendered in codespace

### CODE REVIEW

**Comment by danisztls** [comment]
@marina-chibizova

Hugo was erroring because *MVT* page was drafted and it is referenced by the home page.

Our code is diverging a bit from the original theme so some parameters are different or not working.

I implemented new parameters `navHide` and `navHideLink` to replace usage of `hide`.

I will change the code to honor `bookCollapseSection` param.

Please let me know if you want something else changed.

**Comment by marina-chibizova** [comment]
I replaced MVT with Market Heath on the main page

**Comment by marina-chibizova** [comment]
@danisztls how soon do you think we can merge it?

**Comment by danisztls** [comment]
@marina-chibizova should be good to merge if you don't mind `bookCollapseSection` being addressed in a follow up.

Just to confirm. This is how it looks:

Screenshot from 2023-09-07 01-13-45


And this is how it should look with `bookCollapseSection: true`:

Screenshot from 2023-09-07 01-14-01

> I replaced MVT with Market Heath on the main page

Ok. Should I set MVT as draft again? Not sure if you set `draft: true` just to remove it from navigation. :)

**Comment by marina-chibizova** [comment]
> Not sure if you set draft: true just to remove it from navigation. :)

yes, I did

**Pull request merged**
