### PR TITLE
Grammar Checker Script

### PR DESCRIPTION
**Pull request by JediFaust**
Wrote grammar checker script, need assistance to integrate with github actions, trigger on comment and QA testing. Please, @danisztls, @alxarno help me with that, if possible 👏🏻

### CODE REVIEW

**Comment by alxarno** [comment]
@JediFaust I've added action, it should works. Idk about testing, we test this tools after merge). So let's see what @danisztls and @evgenydmitriev will say about your solution.

P.S. There are [limitations](https://languagetool.org/http-api/#/default) of language tool,  but we have much less text to check I guess.

**Comment by JediFaust** [comment]
Thanks a lot! I think limitation of the API is not an issue for our usage. Will be waiting till merge, and will test it 👍🏻

**Review by alxarno — APPROVED** [review]

**Review by evgenydmitriev — APPROVED** [review]
Sorry, I missed the moment when @alxarno added his changes.

**Comment by evgenydmitriev** [comment]
no need to have a separate trigger, switched to `qualitycheck`

**Pull request merged**
