### PR TITLE
Change headers

### PR DESCRIPTION
**Pull request by marina-chibizova**
making headers more generic and broad, to allow categorization based on entity name, type or type of attack. After approval I will fix headers in existing posts. @danisztls please check that it will not ruin current taxonomy

### CODE REVIEW

**Review by JediFaust — APPROVED** [review]
I agree that making the headers more generic and broad is a great idea. This will indeed offer more flexibility for categorizing based on the entity name, type and type of attack.

**Comment by JediFaust** [comment]
@danisztls Please, let me know when to start requesting headers to match the last changes

**Comment by danisztls** [comment]
@marina-chibizova It looks good.

@JediFaust The new taxonomies will be in effect after #169 merge.

**Comment by danisztls** [comment]
Not sure if this can be useful but Hugo has a template feature called [Archetypes](https://gohugo.io/content-management/archetypes/). I don't think content creators will be using running Hugo locally to benefit from `hugo new` command but they might still benefit from a file that they can copy and use as scaffold.

**Comment by marina-chibizova** [comment]
> they might still benefit from a file that they can copy and use as scaffold.

sure, sounds great. it's something I would like to leverage, as people often struggle with the structure

**Pull request merged**
