### PR TITLE
metrics-docs

### PR DESCRIPTION
**Pull request by marina-chibizova**
I wrote it based on the docs we have + gpt. I made a creative attempt to show possible interpretation steps based on sample data from API. Not sure if it's at all needed there. Let me know what you think

### CODE REVIEW

**Comment by evgenydmitriev** [comment]
Why not make separate pages for each metric and add a bit more of the general description/theory/math, crypto context, and usage examples? I think GPT can help with that.

**Comment by sofiasedlova** [comment]
@marina-chibizova I'm done with my edits

**Review by sofiasedlova — APPROVED** [review]
Let me know if you want me to add demo charts

**Comment by marina-chibizova** [comment]
Thanks @sofiasedlova! charts would be nice, but we can add them later. I'd merge it as is now to finalize the challenge

**Pull request merged**
