### PR TITLE
Update payout rate

### PR DESCRIPTION
**Pull request by jhirschkorn**
Update payout_rate to 3 cents per character on 1 Aug.

### CODE REVIEW

**Comment by danisztls** [comment]
@jhirschkorn Should this change apply to PRs created or merged after 1 Aug?

**Comment by kishoian** [comment]
Will I get the old rate for already written articles?

**Comment by jhirschkorn** [comment]
> @jhirschkorn Should this change apply to PRs created or merged after 1 Aug?

created after 1 aug

**Comment by jhirschkorn** [comment]
> Will I get the old rate for already written articles?

yes

**Comment by evgenydmitriev** [comment]
@kishoian, note the [latest comment](https://github.com/1712n/challenge/issues/97#issuecomment-1650395471) from @jhirschkorn in the issue. We are raising the rates on specific entities we are interested in.

**Review by evgenydmitriev — APPROVED** [review]

**Pull request merged**
