### PR TITLE
Lazarus Update for the Ronin incident

### PR DESCRIPTION
**Pull request by JediFaust**
- Added Lazarus Group involvement with the source
- Fixed and extended headers

### CODE REVIEW

**Review by evgenydmitriev — APPROVED** [review]

**Comment by evgenydmitriev** [comment]
@danisztls can we bring the `tags` back ? We need a generic category for tags that don't fit into the default taxonomy. Also, your recent script restructuring [broke](https://github.com/1712n/dn-institute/actions/runs/5676134938/job/15382413123#step:5:90) the payout action.

FYI @alxarno

**Comment by danisztls** [comment]
@evgenydmitriev will look at it asap

**Comment by danisztls** [comment]
@evgenydmitriev

> Also, your recent script restructuring [broke](https://github.com/1712n/dn-institute/actions/runs/5676134938/job/15382413123#step:5:90) the payout action.

See #196

>  can we bring the tags back ? We need a generic category for tags that don't fit into the default taxonomy.

Sure. `tags` will be a global taxonomy or be under `attacks/incidents` like the other taxonomies (`attack-types` et cetera)?

**Comment by evgenydmitriev** [comment]
> Sure. tags will be a global taxonomy or be under attacks/incidents like the other taxonomies (attack-types et cetera)?

yes

**Comment by jhirschkorn** [comment]
> Thanks, @JediFaust! 1197 characters were added/changed in this [PR](https://github.com/1712n/dn-institute/pull/195.diff). At a rate of 5¢/char your contribution is worth $59.85. @albina-at-inca will process your payment.

@albina-at-inca payout on this should be 2x

**Comment by danisztls** [comment]
Merged #200.

`/payout --multiplier 2` should be working

**Comment by albina-at-inca** [comment]
> > Thanks, @JediFaust! 1197 characters were added/changed in this [PR](https://github.com/1712n/dn-institute/pull/195.diff). At a rate of 5¢/char your contribution is worth $59.85. @albina-at-inca will process your payment.
> 
> @albina-at-inca payout on this should be 2x

Noted. The balance will be added to August pay.

**Pull request merged**
