### PR TITLE
2023-11-08-CoinSpot.md

### PR DESCRIPTION
**Pull request by aholman0725**
CoinSpot hack

### CODE REVIEW

**Review by evgenydmitriev — CHANGES_REQUESTED** [review]
@aholman0725 please check comments in other pull requests you opened. I'm seeing the same mistakes here (file name, links, security failure causes, etc.) I would also advise using ChatGPT 4 to fix styling errors. Take a look at [this comment](https://github.com/1712n/dn-institute/pull/288#pullrequestreview-1708084046).

**Comment by aholman0725** [comment]
@jhirschkorn I've made a few unnecessary changes as I didn't understand what Ev was requesting. Since there are quite a few commits should I delete the pull request and submit a fresh one?

Also wondering if you have any suggestions for a chatgpt alternative as they are not allowing upgrades to gpt4 at the moment. Ev wanted me to use it for the security failure in the articles. Thanks!

**Comment by aholman0725** [comment]
@jhirschkorn I also have a question about an article in which Sinbad has been sanctioned. It connects to a few articles that have already been posted, so I thought it would be a good update, however there is no monetary loss, no specific entity attacked ect. I wanted to see if that's something you think is an acceptable article based on the issue guidelines.

**Comment by aholman0725** [comment]
@evgenydmitriev Corrections made. Please let me know if there are any additional corrections that need to be made.

**Comment by aholman0725** [comment]
ChatGPT4 used to update security failures.

**Review by evgenydmitriev — APPROVED** [review]

**Pull request merged**
