### PR TITLE
Adding a new style checker bot

### PR DESCRIPTION
**Pull request by Kseymur**
This is a pull request from Kseniia Murasheva (https://tbilisi.headhunter.ge/resume/062f4941ff09e352d30039ed1f46794537434d) for Junior LLM Prompt Engineer position

### CODE REVIEW

**Comment by marina-chibizova** [comment]
Hey @Kseymur, thanks for committing to our challenge program! Please take a look at the way our bots are [deployed](https://github.com/1712n/dn-institute/tree/main/.github/workflows) and complete your PR

**Comment by Kseymur** [comment]
Added a new functionality to the existing fact checker bot

**Comment by Kseymur** [comment]
Thank you for your feedback! You were right, I was confused about inputs and structures. I have tried to fix it, but im not sure if it works well in terms of GitHub Actions

**Comment by evgenydmitriev** [comment]
I wouldn't worry about any functionality that isn't possible with the OpenAI API alone. You can probably cover 80% of what's needed with it, and the remaining functionality (like browsing the web) will probably become available soon. Should be easy to integrate it if you keep your bot simple.

**Pull request closed without merging**
