### PR TITLE
Taxonomies: Improve pagination & layout

### LINKED ISSUE #36: Improve taxonomies pagination & layout
We have more and more contributions to the content and now there is a pagination for custodians, with only 10 per page:
image.

Could you change this number to 50? Is there any way to show the taxonomy other than buttons?

### PR DESCRIPTION
**Pull request by danisztls**
Fix #36

### Changes

- Order terms in the book section *(on the right side)* by their size *(n of pages)*
- Order terms in terms list alphabetically
- Increase pagination size to 50 in terms list
- Implement new layout where terms are grouped by their initial letter *(drop cap)*

### CODE REVIEW

**Comment by danisztls** [comment]
@marina-chibizova With custodians list growing will it make sense to make the lists in the book section *(right side)* collapsible?

**Comment by marina-chibizova** [comment]
@danisztls yeah, let's do it collapsible. I would group them by the first letter in the future as Wikipedia does - but for now, it's fine. 
could you sort them alphabetically?

**Comment by danisztls** [comment]
@marina-chibizova Changes made.

**Comment by evgenydmitriev** [comment]
@marina-chibizova are you happy with the changes? We probably need to double-check all article headers if we want to merge this.

**Comment by danisztls** [comment]
> @marina-chibizova are you happy with the changes? We probably need to double-check all article headers if we want to merge this.

We can use a temporary workflow to enforce the new format. Possibly easier than *fixing* ongoing PRs.

```sh
sed -i "s|^categories:|attacks/posts/categories:|" content/attacks/posts/*.md
sed -i "s|^custodians:|attacks/posts/custodians:|" content/attacks/posts/*.md
```

**Comment by marina-chibizova** [comment]
@evgenydmitriev I went through the articles and understood the real cause of the problem I was trying to fix in #36 - people confuse custodian and entity and add custodian header everywhere. I proposed my changes here - #145. 
With them we will have less items in taxonomy, but I would still proceed with this pr to start organizing taxonomies in a way that's close to wikipedia

**Comment by evgenydmitriev** [comment]
Okay, I merged #145. You can now sync this branch with main and proceed with the rest of the changes.

**Comment by danisztls** [comment]
Rebased and fixed conflicts.

**Review by marina-chibizova — APPROVED** [review]

**Comment by marina-chibizova** [comment]
@danisztls I liked how the custodians looked before rebasing, organized by first letter and smaller font

**Comment by danisztls** [comment]
Sorry @marina-chibizova this wasn't intended and not caused by the rebasing the commits but by the taxonomies remap/rename. Fixing it in a follow up PR.

**Pull request merged**
