### PR TITLE
2023-07-22-AlphaPo

### PR DESCRIPTION
**Pull request by JediFaust**

### CODE REVIEW

**Review by evgenydmitriev — APPROVED** [review]

**Comment by evgenydmitriev** [comment]
@JediFaust good catch with the recent news linking the attack to DPRK!

/payout

**Comment by evgenydmitriev** [comment]
@jhirschkorn note the link to DPRK and adjust the payout rate as needed.

**Comment by jhirschkorn** [comment]
> Thanks, @JediFaust! 3209 characters were added/changed in this [PR](https://github.com/1712n/dn-institute/pull/194.diff). At a rate of 5¢/char your contribution is worth $160.45. @albina-at-inca will process your payment.

@albina-at-inca payout on this should be 2x

**Comment by albina-at-inca** [comment]
> > Thanks, @JediFaust! 3209 characters were added/changed in this [PR](https://github.com/1712n/dn-institute/pull/194.diff). At a rate of 5¢/char your contribution is worth $160.45. @albina-at-inca will process your payment.
> 
> @albina-at-inca payout on this should be 2x

Noted.

**Pull request merged**
