### PR TITLE
Market Manipulations Widget

### PR DESCRIPTION
**Pull request by JediFaust**
Added Widget with Metrics and Exchange/Pair selection. Works fine in local environment.
- Uses secrets to access an API key and host, so RAPID_KEY and RAPID_HOST named secrets needed, seems I have no permission to add em. And this part was not tested after final changes to deployment action.
- Pair selection is limited, since universal pairs across all exchanges are those three. There are 800+ pairs in ascendex and quite a lot in others, it might look terrible.

### CODE REVIEW

**Comment by marina-chibizova** [comment]
@JediFaust I added secrets to the repo

**Comment by JediFaust** [comment]
Cannot merge, approval needed

**Comment by marina-chibizova** [comment]
hey @JediFaust I opened your pr in a codespace and the widget doesn't fully render there. Inspect also shows a lot of errors. So we can't approve it at this point

image

**Comment by evgenydmitriev** [comment]
@JediFaust are you planning to make any modifications or we can close this pr?

**Pull request closed without merging**
